{
 "title": "MiniCoders - Service Health",
 "description": "add logs",
 "tags": [
  "minicoders",
  "health"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Logs Metrics Exporter",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/lib/docker/containers/27100ba30136ba4a926ba8c2a9971c1a70e8116fd274625b383c70cb9c6f4ba6/27100ba30136ba4a926ba8c2a9971c1a70e8116fd274625b383c70cb9c6f4ba6-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs Grafana",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/lib/docker/containers/a85705fe634f087d4a456c3df2f7c06f8ed80c89d6b1ce14101840ef9868a042/a85705fe634f087d4a456c3df2f7c06f8ed80c89d6b1ce14101840ef9868a042-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs Loki 1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/lib/docker/containers/11b0a79d836d0efc56db217304e2e124292f2df7bfe3ec23b76d389bb46ea1b0/11b0a79d836d0efc56db217304e2e124292f2df7bfe3ec23b76d389bb46ea1b0-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs Loki 2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/lib/docker/containers/bb0724965349c565b9e53afe8712772da2ac6d149d15e23586b365c8073199e2/bb0724965349c565b9e53afe8712772da2ac6d149d15e23586b365c8073199e2-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Promtail Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"promtail\"} |= ``"
    }
   ]
  },
  {
   "title": "Up - Metrics Exporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "up{job=~\"minicoders_exporter|metrics-exporter|prometheus\"}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Exporter Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"minicoders_exporter\"}"
    }
   ]
  }
 ]
}